/*
Copyright (C) 2023-2026 QuantumNous

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU Affero General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.
*/
import { ArrowRight, Layers3, TrendingDown, Zap } from 'lucide-react'
import { useQuery } from '@tanstack/react-query'
import { useEffect, useMemo } from 'react'
import { useTranslation } from 'react-i18next'

import { PublicLayout } from '@/components/layout'
import { PageTransition } from '@/components/page-transition'
import { normalizeInterfaceLanguage } from '@/i18n/languages'
import { getPerfMetricsSummary } from '@/features/performance-metrics/api'
import { getSuccessRateDotClass } from '@/features/performance-metrics/lib/format'
import { getLobeIcon } from '@/lib/lobe-icon'

import { usePricingData } from '../hooks/use-pricing-data'
import { getDisplayGroupRatio } from '../lib/model-helpers'
import { formatFixedPrice, formatGroupPrice } from '../lib/price'
import type { PricingModel } from '../types'

type DiscountCopy = { title: string; subtitle: string; official: string; actual: string; savings: string; perMillion: string; groups: string; models: string; bestDeal: string; note: string; input: string; output: string; request: string; details: string; categories: Record<string, string> }

const copy: Record<string, DiscountCopy> = {
  zh: { title: '同一模型，分组越多，价格越透明', subtitle: '官方价格与 EMO 实际价格并排展示。一个模型在多个分组中会分别列出，直接看到每个分组能省多少。', official: '官方价', actual: 'EMO 实际价', savings: '立省', perMillion: '/ 1M tokens', groups: '优惠分组', models: '可用模型', bestDeal: '最高优惠', note: '价格以当前模型配置为准；不同分组可能有不同的实际价格。', input: '输入', output: '输出', request: '每次请求', details: '价格明细', categories: { GPT: 'GPT', Claude: 'Claude', Gemini: 'Gemini', DeepSeek: 'DeepSeek', KIMI: 'KIMI' } },
  en: { title: 'One model. Every group. Every price.', subtitle: 'Compare official rates with the real EMO price side by side. Models available in multiple groups are listed separately so every deal is clear.', official: 'Official', actual: 'EMO price', savings: 'Save', perMillion: '/ 1M tokens', groups: 'Discount groups', models: 'Available models', bestDeal: 'Best deal', note: 'Prices follow the current model configuration. The same model may have a different price in each group.', input: 'Input', output: 'Output', request: 'per request', details: 'Price details', categories: { GPT: 'GPT', Claude: 'Claude', Gemini: 'Gemini', DeepSeek: 'DeepSeek', KIMI: 'KIMI' } },
  ja: { title: '同じモデルでも、グループごとの価格を公開', subtitle: '公式価格と EMO の実際の価格を並べて表示します。複数グループのモデルも、グループごとに明確に比較できます。', official: '公式価格', actual: 'EMO 価格', savings: 'お得', perMillion: '/ 1M tokens', groups: '割引グループ', models: '利用可能モデル', bestDeal: '最大割引', note: '価格は現在のモデル設定に基づきます。同じモデルでもグループにより価格が異なる場合があります。', input: '入力', output: '出力', request: 'リクエストごと', details: '料金の詳細', categories: { GPT: 'GPT', Claude: 'Claude', Gemini: 'Gemini', DeepSeek: 'DeepSeek', KIMI: 'KIMI' } },
}
const categoryOrder = ['GPT', 'Claude', 'Gemini', 'DeepSeek', 'KIMI']
function getCopy(language: string) { const normalized = normalizeInterfaceLanguage(language); return copy[normalized === 'zhCN' ? 'zh' : normalized] ?? copy.en }
function getCategory(modelName: string) { const n = modelName.toLowerCase(); if (n.includes('claude')) return 'Claude'; if (n.includes('gemini')) return 'Gemini'; if (n.includes('deepseek')) return 'DeepSeek'; if (n.includes('kimi')) return 'KIMI'; if (n.includes('gpt')) return 'GPT'; return null }
function ratioLabel(language: string, ratio: number) { const n = normalizeInterfaceLanguage(language); const p = Math.round(ratio * 100); if (n === 'zhCN') return `${Math.round(ratio * 10)} 折`; if (n === 'ja') return `${p}%`; return `${p}%` }
function price(model: PricingModel, group: string, groupRatio: Record<string, number>, type: 'input' | 'output', official: boolean) { const ratios = official ? { [group]: 1 } : groupRatio; return model.quota_type === 1 ? formatFixedPrice(model, group, false, 1, 1, ratios) : formatGroupPrice(model, group, type, 'M', false, 1, 1, ratios) }

function PriceLine({ model, group, groupRatio, label, type, text }: { model: PricingModel; group: string; groupRatio: Record<string, number>; label: string; type: 'input' | 'output'; text: DiscountCopy }) {
  return <div className='flex items-center justify-between gap-3 border-t border-border/60 py-1.5 first:border-t-0'><span className='text-muted-foreground text-[11px] font-medium'>{label}</span><div className='flex min-w-0 items-baseline gap-1.5 text-right'><span className='text-muted-foreground text-[11px] line-through'>{price(model, group, groupRatio, type, true)}</span><ArrowRight className='text-primary/50 size-3 shrink-0' /><span className='text-foreground font-mono text-xs font-bold sm:text-sm'>{price(model, group, groupRatio, type, false)}</span><span className='text-muted-foreground hidden text-[9px] xl:inline'>{model.quota_type === 1 ? text.request : text.perMillion}</span></div></div>
}

export function DiscountModels() {
  const { i18n } = useTranslation(); const { models, groupRatio, isLoading } = usePricingData('/api/discount-pricing')
  const perfQuery = useQuery({ queryKey: ['perf-metrics-summary', 24], queryFn: () => getPerfMetricsSummary(24), staleTime: 60 * 1000, retry: false })
  const text = getCopy(i18n.resolvedLanguage ?? i18n.language); const language = i18n.resolvedLanguage ?? i18n.language
  const perfMap = useMemo(() => new Map((perfQuery.data?.data?.models ?? []).map((item) => [item.model_name, item])), [perfQuery.data])
  useEffect(() => { document.title = `${text.title} | EMO API` }, [text.title])
  const discountedGroups = useMemo(() => Object.entries(groupRatio).filter(([, ratio]) => ratio > 0 && ratio < 1).map(([group, ratio]) => ({ group, ratio, models: (models || []).filter((model) => model.enable_groups?.includes(group)).map((model) => ({ ...model, category: getCategory(model.model_name), displayRatio: getDisplayGroupRatio(model, group) })).filter((model) => model.displayRatio > 0 && model.displayRatio < 1).sort((a, b) => { const d = (a.category ? categoryOrder.indexOf(a.category) : categoryOrder.length) - (b.category ? categoryOrder.indexOf(b.category) : categoryOrder.length); return d || a.model_name.localeCompare(b.model_name) }) })).filter((section) => section.models.length > 0).sort((a, b) => a.ratio - b.ratio), [groupRatio, models])
  const stats = useMemo(() => { const unique = new Set(discountedGroups.flatMap((g) => g.models.map((m) => m.model_name))); const best = discountedGroups.reduce((v, s) => Math.min(v, s.ratio), 1); return { groups: discountedGroups.length, models: unique.size, best } }, [discountedGroups])
  return <PublicLayout showMainContainer={false}><PageTransition className='mx-auto w-full max-w-[1500px] px-4 pt-20 pb-16 sm:px-8'>
    <section className='relative isolate overflow-hidden rounded-3xl bg-gradient-to-br from-slate-950 via-primary/90 to-indigo-700 px-6 py-10 text-white shadow-xl shadow-primary/15 sm:px-10 sm:py-12'><div className='pointer-events-none absolute -right-24 -top-28 size-80 rounded-full bg-cyan-300/20 blur-3xl' /><div className='pointer-events-none absolute -bottom-36 left-1/3 size-96 rounded-full bg-fuchsia-400/20 blur-3xl' /><div className='relative grid gap-8 lg:grid-cols-[1.2fr_0.8fr] lg:items-end'><div><h1 className='max-w-3xl text-4xl font-black tracking-tight sm:text-5xl'>{text.title}</h1><p className='mt-4 max-w-2xl text-sm leading-6 text-white/75 sm:text-base'>{text.subtitle}</p></div><div className='grid grid-cols-3 gap-2'>{[{ icon: Layers3, value: stats.groups, label: text.groups }, { icon: Zap, value: stats.models, label: text.models }, { icon: TrendingDown, value: `${Math.round((1 - stats.best) * 100)}%`, label: text.bestDeal }].map(({ icon: Icon, value, label }) => <div key={label} className='rounded-xl border border-white/15 bg-white/10 p-3 backdrop-blur sm:p-4'><div className='flex items-center justify-between gap-2'><Icon className='size-4 text-cyan-200' /><div className='text-xl font-black tracking-tight sm:text-2xl'>{value}</div></div><div className='mt-3 text-[11px] text-white/60 sm:text-xs'>{label}</div></div>)}</div></div></section>
    <div className='mt-7 flex flex-wrap items-baseline gap-x-3 gap-y-1'><div className='bg-primary size-2 rounded-full' /><h2 className='text-lg font-bold tracking-tight sm:text-xl'>{text.details}</h2><span className='text-muted-foreground text-xs'>{text.note}</span></div>
    {isLoading ? <div className='mt-4 grid gap-4 lg:grid-cols-2'>{[1, 2, 3, 4].map((item) => <div key={item} className='bg-muted/40 h-60 animate-pulse rounded-2xl border' />)}</div> : <div className='mt-4 grid items-start gap-4 lg:grid-cols-2'>{discountedGroups.map((section) => <section key={section.group} className='bg-background overflow-hidden rounded-2xl border shadow-sm'><div className='from-primary/10 via-primary/5 flex items-center justify-between gap-3 border-b bg-gradient-to-r to-transparent px-4 py-3'><div className='flex min-w-0 items-center gap-2.5'><h3 className='truncate text-base font-bold'>{section.group}</h3><span className='bg-primary text-primary-foreground shrink-0 rounded-full px-2 py-0.5 text-[11px] font-bold'>{ratioLabel(language, section.ratio)}</span><span className='text-muted-foreground shrink-0 text-[11px]'>{section.models.length} {text.models}</span></div><div className='text-primary shrink-0 text-sm font-black'>{text.savings} {Math.round((1 - section.ratio) * 100)}%</div></div><div className='divide-y'>{section.models.map((model) => { const iconKey = model.icon || model.vendor_icon; const rate = perfMap.get(model.model_name)?.success_rate; const hasRate = typeof rate === 'number' && Number.isFinite(rate); return <article key={`${section.group}-${model.model_name}`} className='grid gap-3 px-4 py-3 transition-colors hover:bg-muted/20 sm:grid-cols-[minmax(0,0.9fr)_minmax(260px,1.1fr)] sm:items-center'><div className='flex min-w-0 items-center gap-2.5'><div className='bg-muted/60 flex size-9 shrink-0 items-center justify-center rounded-lg'>{iconKey ? getLobeIcon(iconKey, 26) : <span className='font-bold'>{model.model_name.charAt(0)}</span>}</div><div className='min-w-0 flex-1'><div className='flex min-w-0 items-center gap-1.5'><h4 className='truncate font-mono text-xs font-bold sm:text-sm'>{model.model_name}</h4><span className='bg-primary/10 text-primary shrink-0 rounded px-1.5 py-0.5 text-[9px] font-bold'>-{Math.round((1 - model.displayRatio) * 100)}%</span></div><div className='text-muted-foreground mt-0.5 flex items-center gap-1.5 text-[10px]'>{model.category && <span>{text.categories[model.category] ?? model.category}</span>}{hasRate && <><span>·</span><span className='inline-flex items-center gap-1'><span className={`size-1.5 rounded-full ${getSuccessRateDotClass(rate)}`} />{rate.toFixed(1)}%</span></>}</div></div></div><div className='bg-muted/20 rounded-lg px-3'>{model.quota_type === 1 ? <PriceLine model={model} group={section.group} groupRatio={groupRatio} label={text.request} type='input' text={text} /> : <><PriceLine model={model} group={section.group} groupRatio={groupRatio} label={text.input} type='input' text={text} /><PriceLine model={model} group={section.group} groupRatio={groupRatio} label={text.output} type='output' text={text} /></>}</div></article> })}</div></section>)}</div>}
  </PageTransition></PublicLayout>
}
